# Generated by Django 2.1.7 on 2019-04-18 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo3.Problem'),
        ),
    ]
