# Generated by Django 2.1.7 on 2019-04-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='oshu',
            field=models.IntegerField(default=0),
        ),
    ]
